DesafioPrevidencia.MVC/Controllers/CarteiraController.cs
using AutoMapper;
using DesafioPrevidencia.Aplicacao.Interfaces;
using DesafioPrevidencia.MVC.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DesafioPrevidencia.MVC.Controllers
{
    public class CarteiraController : Controller
    {
        private readonly ICarteiraAplicacao _carteiraApp;
        private readonly IUsuarioAplicacao _usuarioApp;
        private readonly IRespostasFormularioAplicacao _respostasFormularioApp;
        private IMapper _mapper;

        public CarteiraController(ICarteiraAplicacao carteiraApp, IUsuarioAplicacao usuarioApp, IRespostasFormularioAplicacao respostasFormularioApp, IMapper mapper)
        {
            _carteiraApp = carteiraApp;
            _usuarioApp = usuarioApp;
            _respostasFormularioApp = respostasFormularioApp;
            _mapper = mapper;
        }

        // GET: Carteira
        public ActionResult Index()
        {
            var usuario = _usuarioApp.ObterUsuarioPeloEmail(HttpContext.User.Identity.Name);
            if (usuario != null)
            {
                ViewBag.Logado = "S";
                if (usuario.Carteira != null)
                {
                    var carteiraModel = _mapper.Map<CarteiraModel>(usuario.Carteira);
                    return View(carteiraModel);
                }
                else
                {
                    var carteiraModel = new CarteiraModel();
                    ViewBag.Mensagem = "Você não possui nenhuma carteira selecionada";
                    var respostasFormulariodom = _respostasFormularioApp.BuscarPoIdUsuario(usuario.UsuarioId);
                    if (respostasFormulariodom != null)
                        ViewBag.Formulario = "Respondido";
                    else
                        ViewBag.Formulario = "Não respondido";
                    return View(carteiraModel);
                }
            }
            else
            {
                ViewBag.Mensagem = "Você precisa estar logado para ver esta opção.";
                ViewBag.Logado = "N";
                return View(new CarteiraModel());
            }
        }

        public ActionResult Escolher(int CarteiraId)
        {
            var usuario = _usuarioApp.ObterUsuarioPeloEmail(HttpContext.User.Identity.Name);
            var carteiraDominio = _carteiraApp.BuscarPorUsuario(usuario, CarteiraId);
            if (carteiraDominio != null)
            {
                var carteiraModel = _mapper.Map<IEnumerable<CarteiraModel>>(carteiraDominio);
                return View(carteiraModel);
            }
            else
            {
                var carteiraModel = _mapper.Map<IEnumerable<CarteiraModel>>(_carteiraApp.GetAll());
                ViewBag.Message = "Erro";
                return View(carteiraModel);
            }
        }

    }
}

DesafioPrevidencia.MVC/Controllers/RespostasFormularioController.cs
using AutoMapper;
using DesafioPrevidencia.Aplicacao.Interfaces;
using DesafioPrevidencia.Dominio.Entidades;
using DesafioPrevidencia.MVC.Models;
using System;
using System.Web.Mvc;

namespace DesafioPrevidencia.MVC.Controllers
{
    public class RespostasFormularioController : Controller
    {
        private readonly IRespostasFormularioAplicacao _respostasFormularioApp;
        private readonly IUsuarioAplicacao _usuarioApp;
        private IMapper _mapper;

        public RespostasFormularioController(IRespostasFormularioAplicacao respostasFormularioApp, IUsuarioAplicacao usuarioApp, IMapper mapper)
        {
            _respostasFormularioApp = respostasFormularioApp;
            _usuarioApp = usuarioApp;
            _mapper = mapper;
        }

        // GET: RespostasForumlario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RespostasForumlario/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RespostasFormularioModel respostasFormularioModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!UsuarioJaRespondeu())
                    {
                        var respostasDominio = _mapper.Map<RespostasFormulario>(respostasFormularioModel);
                        respostasDominio.UsuarioId = _usuarioApp.ObterUsuarioPeloEmail(HttpContext.User.Identity.Name).UsuarioId;

                        _respostasFormularioApp.Add(_respostasFormularioApp.MontarPerfilRespostasFormulario(respostasDominio));
                    }
                }

                return RedirectToAction("Index", "Usuario");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: RespostasForumlario/Edit/5
        public ActionResult Edit()
        {
            var emailUsuario = HttpContext.User.Identity.Name;
            if (!string.IsNullOrEmpty(emailUsuario))
            {
                var respostasFormulario = _respostasFormularioApp.BuscarPoIdUsuario(_usuarioApp.ObterUsuarioPeloEmail(emailUsuario).UsuarioId);

                if (respostasFormulario != null)
                {
                    return View(_mapper.Map<RespostasFormularioModel>(respostasFormulario));
                }
                else
                {
                    return RedirectToAction("Create");
                }
            }
            else
            {
                return View();
            }

        }

        // POST: RespostasForumlario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RespostasFormularioModel respostasFormularioModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var respostasDominio = _mapper.Map<RespostasFormulario>(respostasFormularioModel);
                    _respostasFormularioApp.Update(_respostasFormularioApp.MontarPerfilRespostasFormulario(respostasDominio));
                }
                return RedirectToAction("Index", "Usuario");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public bool UsuarioJaRespondeu()
        {
            return _respostasFormularioApp.BuscarPoIdUsuario(_usuarioApp.ObterUsuarioPeloEmail(HttpContext.User.Identity.Name).UsuarioId) != null ? true : false;
        }
    }
}

DesafioPrevidencia.MVC/Controllers/UsuarioController.cs
using AutoMapper;
using DesafioPrevidencia.Aplicacao.Interfaces;
using DesafioPrevidencia.Dominio.Entidades;
using DesafioPrevidencia.MVC.Models;
using System;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace DesafioPrevidencia.MVC.Controllers
{
    public class UsuarioController : Controller
    {

        private readonly IUsuarioAplicacao _usuarioApp;
        private readonly IRespostasFormularioAplicacao _respostasFormularioApp;
        private IMapper _mapper;

        public UsuarioController(IUsuarioAplicacao usuarioApp, IRespostasFormularioAplicacao respostasFormularioApp, IMapper mapper)
        {
            _usuarioApp = usuarioApp;
            _respostasFormularioApp = respostasFormularioApp;
            _mapper = mapper;
        }

        // GET: Usuario
        public ActionResult Index()
        {
            var usuario = _usuarioApp.ObterUsuarioPeloEmail(HttpContext.User.Identity.Name);
            if (usuario.Carteira == null)
            {
                ViewBag.Carteira = "Não há carteira associada a este usuario";
            }
            var respostasFormulario = _respostasFormularioApp.BuscarPoIdUsuario(usuario.UsuarioId);
            if (respostasFormulario == null)
            {
                ViewBag.PerfilInvesidor = "Sem Perfil, favor responder o formulário";
            }
            else
                ViewBag.PerfilInvesidor = respostasFormulario.PerfilInvestidor.Nome;

            var usuarioViewModel = _mapper.Map<UsuarioModel>(usuario);
            return View(usuarioViewModel);
        }

        //Registration Action
        [HttpGet]
        public ActionResult RegistrarUsuario()
        {
            return View();
        }
        //Registration POST action 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegistrarUsuario(UsuarioModel usuarioModel)
        {
            bool status = false;
            string mensagem = "";

            if (ModelState.IsValid)
            {
                #region Verificar se email já existe
                var jahExiste = EmailExistente(usuarioModel.Email);
                if (jahExiste)
                {
                    ModelState.AddModelError("EmailExiste", "E-mail já cadastrado.");
                    return View(usuarioModel);
                }
                #endregion

                #region  Hash da senha 
                usuarioModel.Senha = Crypto.Hash(usuarioModel.Senha);
                usuarioModel.ConfirmarSenha = Crypto.Hash(usuarioModel.ConfirmarSenha);
                usuarioModel.DataCadastro = DateTime.Now;
                #endregion

                #region Salvar usuário no BD
                try
                {
                    var usuarioDominio = _mapper.Map<Usuario>(usuarioModel);
                    _usuarioApp.Add(usuarioDominio);
                    mensagem = "Usuário criado com sucesso.";
                    status = true;
                }
                catch { }

                #endregion
            }
            else
            {
                mensagem = "Requisição Inválida.";
            }

            ViewBag.Message = mensagem;
            ViewBag.Status = status;
            return View(usuarioModel);
        }

        //Login 
        [HttpGet]
        public ActionResult Login()
        {
            ViewBag.Message = string.Empty;
            return View();
        }

        //Login POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(UsuarioLoginModel login, string ReturnUrl = "")
        {
            string mensagem = "";
            var v = _usuarioApp.ObterUsuarioPeloEmail(login.Email);
            if (v != null)
            {

                if (string.Compare(Crypto.Hash(login.Senha), v.Senha) == 0)
                {
                    int timeout = login.ManterConectado ? 525600 : 20; // 525600 min = 1 year
                    var ticket = new FormsAuthenticationTicket(login.Email, login.ManterConectado, timeout);
                    string encrypted = FormsAuthentication.Encrypt(ticket);
                    var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encrypted);
                    cookie.Expires = DateTime.Now.AddMinutes(timeout);
                    cookie.HttpOnly = true;
                    Response.Cookies.Add(cookie);


                    if (Url.IsLocalUrl(ReturnUrl))
                    {
                        return Redirect(ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    mensagem = "Credenciais inválidas.";
                }
            }
            else
            {
                mensagem = "Credenciais inválidas.";
            }

            ViewBag.Message = mensagem;
            return View();
        }

        //Logout
        [Authorize]
        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [NonAction]
        public bool EmailExistente(string email)
        {
            var v = _usuarioApp.ObterUsuarioPeloEmail(email);
            return v != null;
        }

    }
}

DesafioPrevidencia.MVC/Views/Usuario/Index.cshtml
@model DesafioPrevidencia.MVC.Models.UsuarioModel

@{
    ViewBag.Title = "Index";
}

<h2>Usuário</h2>

<div>
    <h4>Dados do Usuário</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.Label("Carteira Selecionada")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Carteira.Descricao) @ViewBag.Carteira
        </dd>
        <dt>
            @Html.Label("Perfil de Investidor")
        </dt>
        <dd>
            @ViewBag.PerfilInvesidor
        </dd>
    </dl>
</div>
<p>
    @if (ViewBag.PerfilInvesidor != "Sem Perfil, favor responder o formulário")
    {
       <p> @Html.ActionLink("Selecionar ou alterar carteira", "Index", "Carteira")</p>
    }
    @Html.ActionLink("Preencher/Alterar Formulário de Perfil", "Edit", "RespostasFormulario") |
</p>

DesafioPrevidencia.MVC/Views/Usuario/Login.cshtml
@model DesafioPrevidencia.MVC.Models.UsuarioLoginModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @if (ViewBag.Message != "")
        {
            <div class="text-danger">*@ViewBag.Message</div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManterConectado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ManterConectado)
                    @Html.ValidationMessageFor(model => model.ManterConectado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Avançar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cadastrar Usuário", "RegistrarUsuario", "Usuario")
</div>


@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

DesafioPrevidencia.MVC/Views/Usuario/RegistrarUsuario.cshtml
@model DesafioPrevidencia.MVC.Models.UsuarioModel

@{
    ViewBag.Title = "Registrar Usuário";
}

<h2>Registrar Usuário</h2>


@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
    if (ViewBag.Message != null)
    {
        <div class="alert alert-success">
            <strong>Sucesso!</strong>@ViewBag.Message
        </div>
    }
}
else
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <h4>Insira seus dados</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmarSenha, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ConfirmarSenha, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ConfirmarSenha, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Criar Usuário" class="btn btn-default" />
                </div>
            </div>
        </div>
        if (ViewBag.Status != null && Convert.ToBoolean(!ViewBag.Status) && ViewBag.Message != null)
        {
            <div class="alert alert-danger">
                <strong>Erro!</strong>@ViewBag.Message
            </div>
        }
    }
}

<div>
    @Html.ActionLink("Login", "Login")
</div>

@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}