DesafioPrevidencia.MVC/Controllers/CarteiraController.cs
using AutoMapper;
using DesafioPrevidencia.Aplicacao.Interfaces;
using DesafioPrevidencia.MVC.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DesafioPrevidencia.MVC.Controllers
{
    public class CarteiraController : Controller
    {
        private readonly ICarteiraAplicacao _carteiraApp;
        private readonly IUsuarioAplicacao _usuarioApp;
        private readonly IRespostasFormularioAplicacao _respostasFormularioApp;
        private IMapper _mapper;

        public CarteiraController(ICarteiraAplicacao carteiraApp, IUsuarioAplicacao usuarioApp, IRespostasFormularioAplicacao respostasFormularioApp, IMapper mapper)
        {
            _carteiraApp = carteiraApp;
            _usuarioApp = usuarioApp;
            _respostasFormularioApp = respostasFormularioApp;
            _mapper = mapper;
        }

        // GET: Carteira
        public ActionResult Index()
        {
            var usuario = _usuarioApp.ObterUsuarioPeloEmail(HttpContext.User.Identity.Name);
            if (usuario != null)
            {
                ViewBag.Logado = "S";
                if (usuario.Carteira != null)
                {
                    var carteiraModel = _mapper.Map<CarteiraModel>(usuario.Carteira);
                    return View(carteiraModel);
                }
                else
                {
                    var carteiraModel = new CarteiraModel();
                    ViewBag.Mensagem = "Você não possui nenhuma carteira selecionada";
                    var respostasFormulariodom = _respostasFormularioApp.BuscarPoIdUsuario(usuario.UsuarioId);
                    if (respostasFormulariodom != null)
                        ViewBag.Formulario = "Respondido";
                    else
                        ViewBag.Formulario = "Não respondido";
                    return View(carteiraModel);
                }
            }
            else
            {
                ViewBag.Mensagem = "Você precisa estar logado para ver esta opção.";
                ViewBag.Logado = "N";
                return View(new CarteiraModel());
            }
        }

        public ActionResult Escolher(int CarteiraId)
        {
            var usuario = _usuarioApp.ObterUsuarioPeloEmail(HttpContext.User.Identity.Name);
            var carteiraDominio = _carteiraApp.BuscarPorUsuario(usuario, CarteiraId);
            if (carteiraDominio != null)
            {
                var carteiraModel = _mapper.Map<IEnumerable<CarteiraModel>>(carteiraDominio);
                return View(carteiraModel);
            }
            else
            {
                var carteiraModel = _mapper.Map<IEnumerable<CarteiraModel>>(_carteiraApp.GetAll());
                ViewBag.Message = "Erro";
                return View(carteiraModel);
            }
        }

    }
}

DesafioPrevidencia.MVC/Controllers/RespostasFormularioController.cs
using AutoMapper;
using DesafioPrevidencia.Aplicacao.Interfaces;
using DesafioPrevidencia.Dominio.Entidades;
using DesafioPrevidencia.MVC.Models;
using System;
using System.Web.Mvc;

namespace DesafioPrevidencia.MVC.Controllers
{
    public class RespostasFormularioController : Controller
    {
        private readonly IRespostasFormularioAplicacao _respostasFormularioApp;
        private readonly IUsuarioAplicacao _usuarioApp;
        private IMapper _mapper;

        public RespostasFormularioController(IRespostasFormularioAplicacao respostasFormularioApp, IUsuarioAplicacao usuarioApp, IMapper mapper)
        {
            _respostasFormularioApp = respostasFormularioApp;
            _usuarioApp = usuarioApp;
            _mapper = mapper;
        }

        // GET: RespostasForumlario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RespostasForumlario/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RespostasFormularioModel respostasFormularioModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!UsuarioJaRespondeu())
                    {
                        var respostasDominio = _mapper.Map<RespostasFormulario>(respostasFormularioModel);
                        respostasDominio.UsuarioId = _usuarioApp.ObterUsuarioPeloEmail(HttpContext.User.Identity.Name).UsuarioId;

                        _respostasFormularioApp.Add(_respostasFormularioApp.MontarPerfilRespostasFormulario(respostasDominio));
                    }
                }

                return RedirectToAction("Index", "Usuario");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: RespostasForumlario/Edit/5
        public ActionResult Edit()
        {
            var emailUsuario = HttpContext.User.Identity.Name;
            if (!string.IsNullOrEmpty(emailUsuario))
            {
                var respostasFormulario = _respostasFormularioApp.BuscarPoIdUsuario(_usuarioApp.ObterUsuarioPeloEmail(emailUsuario).UsuarioId);

                if (respostasFormulario != null)
                {
                    return View(_mapper.Map<RespostasFormularioModel>(respostasFormulario));
                }
                else
                {
                    return RedirectToAction("Create");
                }
            }
            else
            {
                return View();
            }

        }

        // POST: RespostasForumlario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RespostasFormularioModel respostasFormularioModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var respostasDominio = _mapper.Map<RespostasFormulario>(respostasFormularioModel);
                    _respostasFormularioApp.Update(_respostasFormularioApp.MontarPerfilRespostasFormulario(respostasDominio));
                }
                return RedirectToAction("Index", "Usuario");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public bool UsuarioJaRespondeu()
        {
            return _respostasFormularioApp.BuscarPoIdUsuario(_usuarioApp.ObterUsuarioPeloEmail(HttpContext.User.Identity.Name).UsuarioId) != null ? true : false;
        }
    }
}

DesafioPrevidencia.MVC/Controllers/SolicitacaoController.cs
using AutoMapper;
using DesafioPrevidencia.Aplicacao.Interfaces;
using DesafioPrevidencia.Dominio.Entidades;
using DesafioPrevidencia.MVC.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DesafioPrevidencia.MVC.Controllers
{
    public class SolicitacaoController : Controller
    {
        private readonly ISolicitacaoAplicacao _solicitacaoApp;
        private readonly ICarteiraAplicacao _carteiraApp;
        private readonly IUsuarioAplicacao _usuarioApp;
        private IMapper _mapper;

        public SolicitacaoController(ISolicitacaoAplicacao solicitacaoApp, ICarteiraAplicacao carteiraApp, IUsuarioAplicacao usuarioApp, IMapper mapper)
        {
            _solicitacaoApp = solicitacaoApp;
            _carteiraApp = carteiraApp;
            _usuarioApp = usuarioApp;
            _mapper = mapper;
        }

        // GET: Solicitacao
        public ActionResult Index()
        {
            var emailUsuario = HttpContext.User.Identity.Name;
            if (!string.IsNullOrEmpty(emailUsuario))
            {
                var solicitacaoDominio = _solicitacaoApp.BuscarPoIdUsuario(_usuarioApp.ObterUsuarioPeloEmail(emailUsuario).UsuarioId);
                return View(_mapper.Map<IEnumerable<SolicitacaoModel>>(solicitacaoDominio));
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string Protocolo)
        {
            return RedirectToAction("ResultadoPesquisa", new { Protocolo });
        }

        // GET: Carteira/Details/5
        public ActionResult Escolher()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Escolher(int Selecionada)
        {
            try
            {
                var usuario = _usuarioApp.ObterUsuarioPeloEmail(HttpContext.User.Identity.Name);
                var solicitacaoDominio = _solicitacaoApp.MontarSolicitacao(Selecionada, usuario.UsuarioId);
                if (solicitacaoDominio != null)
                {
                    _solicitacaoApp.Add(solicitacaoDominio);
                    return View(_mapper.Map<SolicitacaoModel>(solicitacaoDominio));
                }
                else
                {
                    ViewBag.Pendente = "Há uma solicitação ainda em aberto, não é possível realizar outra.";
                    return View();
                }

            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public ActionResult ResultadoPesquisa()
        {
            return View(new List<SolicitacaoModel>());
        }

        // GET: Solicitacao/Create
        public ActionResult Pesquisa()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ResultadoPesquisa(string Protocolo)
        {
            var solicitacaoDominio = _solicitacaoApp.BuscarPorProtocolo(Protocolo);
            if (solicitacaoDominio != null)
                return RedirectToAction("Resultado", new { solicitacaoDominio.SolicitacaoId });
            else
                return View();
        }

        public ActionResult Resultado(int solicitacaoId)
        {

            if (solicitacaoId == 0)
            {
                var solicitacaoDominio = _solicitacaoApp.BuscarPoIdUsuario(_usuarioApp.ObterUsuarioPeloEmail(HttpContext.User.Identity.Name).UsuarioId);
                return View(_mapper.Map<IEnumerable<SolicitacaoModel>>(solicitacaoDominio));
            }
            else
            {
                List<Solicitacao> resultado = new List<Solicitacao>();
                resultado.Add(_solicitacaoApp.GetById(solicitacaoId));
                return View("ResultadoPesquisa", _mapper.Map<IEnumerable<SolicitacaoModel>>(resultado));
            }

        }

    }
}

DesafioPrevidencia.MVC/Views/Carteira/Escolher.cshtml
@model IEnumerable<DesafioPrevidencia.MVC.Models.CarteiraModel>

@{
    ViewBag.Title = "Carteiras";
}

<h2>Carteiras Indicadas< w/h2>
<p>
    @if (ViewBag.Message != null)
    {
        <div class="alert alert-danger">
            <strong>Erro!</strong>@ViewBag.Message
        </div>
    }
</p>
@using (Html.BeginForm("Escolher", "Solicitacao", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <table class="table">
        <tr>
            <td></td>
            <th>
                @Html.DisplayNameFor(model => model.Composicao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rentabilidade)
            </th>
            <th>
                @Html.Label("Perfil")
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.RadioButton("Selecionada", item.CarteiraId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Composicao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rentabilidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PerfilInvestidor.Nome)
                </td>
            </tr>
        }
    </table>

    <input type="submit" value="Enviar" />
}

DesafioPrevidencia.MVC/Views/Carteira/Index.cshtml
@model DesafioPrevidencia.MVC.Models.CarteiraModel

@{
    ViewBag.Title = "Carteira";
}

<h2>Carteira</h2>

<div>
    <h4>Sua Carteira</h4>
    <hr />
    @if (Model.CarteiraId > 0)
    {
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Composicao)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Composicao)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Rentabilidade)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Rentabilidade)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Descricao)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Descricao)
            </dd>

            <dt>
                @Html.Label("Perfil Investidor")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PerfilInvestidor.Nome)
            </dd>

        </dl>
    }
    else
    {
        <p>@ViewBag.Mensagem</p>

        if (ViewBag.Logado == "S")
        {
            <p>Formulário de Perfil : @ViewBag.Formulario</p>
        }
    }
</div>

@if (ViewBag.Formulario == "Respondido" || Model.PerfilInvestidorId > 0)
{
    <p>@Html.ActionLink("Escolher/Alterar Carteira", "Escolher", "Carteira", new { CarteiraId = Model.CarteiraId }, null)</p>
}
else
{
    <p>Para escolher uma carteira, você precisa responder o formulário de perfil de investidor</p>
}
@if (ViewBag.Logado == "S")
{
    @Html.ActionLink("Preencher/Alterar Formulário de Perfil", "Edit", "RespostasFormulario")
}